import admin from 'firebase-admin';
import { type AuthorizedActor } from './authorize.js';
import { HttpError } from './http-errors.js';
import { getAdminFirestore } from './firebase-admin.js';
import { gradeServerQuestionSnapshot, toClientQuestion, type LmsAnswer } from '../../shared/lms-domain.js';

const now = admin.firestore.FieldValue.serverTimestamp();
const POLICY_STATE = 'pending_human_policy' as const;
type Firestore = FirebaseFirestore.Firestore;
const dbOr = (db?: Firestore): Firestore => db ?? getAdminFirestore();

async function assertTrainingProfessional(db: Firestore, uid: string) {
  const professional = await db.collection('professionals').doc(uid).get();
  if (!professional.exists || professional.data()?.lifecycle?.approval?.state !== 'approved') throw new HttpError(403, 'TRAINING_PROFESSIONAL_REQUIRED', 'Training is available only to approved professionals');
  return professional.data()!;
}
function audit(db: Firestore, tx: FirebaseFirestore.Transaction, actorUid: string, action: string, target: string, metadata: Record<string, unknown> = {}) { tx.create(db.collection('audit_log').doc(), { actorUid, action, target, metadata, createdAt: now }); }
function safeProgress(data: FirebaseFirestore.DocumentData | undefined) { return { moduleId: String(data?.moduleId ?? ''), lessonsCompleted: Array.isArray(data?.lessonsCompleted) ? data.lessonsCompleted.map(String) : [], evaluation: data?.evaluation?.state === 'submitted' ? { state: 'submitted', scorePercent: Number(data.evaluation.scorePercent ?? 0), policyState: POLICY_STATE } : null, updatedAt: data?.updatedAt ?? null }; }

export async function getLmsCatalog(input: { actor: AuthorizedActor; professionalUid?: string; db?: Firestore }) {
  const db = dbOr(input.db); const targetUid = input.professionalUid && input.professionalUid !== input.actor.uid ? input.professionalUid : input.actor.uid;
  if (targetUid !== input.actor.uid && !input.actor.permissions.includes('training.review')) throw new HttpError(403, 'PERMISSION_DENIED', 'Training review permission is required');
  const professional = await assertTrainingProfessional(db, targetUid);
  const [moduleSnap, lessonSnap, progressSnap] = await Promise.all([db.collection('modules').where('status', '==', 'published').get(), db.collection('lessons').where('status', '==', 'published').get(), db.collection('lms_progress').doc(targetUid).collection('modules').get()]);
  const modules = moduleSnap.docs.map((doc) => ({ id: doc.id, ...doc.data() } as FirebaseFirestore.DocumentData));
  const lessons = lessonSnap.docs.map((doc) => ({ id: doc.id, ...doc.data() } as FirebaseFirestore.DocumentData));
  modules.sort((a, b) => Number(a.order ?? 0) - Number(b.order ?? 0)); lessons.sort((a, b) => Number(a.order ?? 0) - Number(b.order ?? 0));
  return { professional: { uid: targetUid, trainingState: professional.lifecycle?.training?.state ?? 'not_started', certificationState: professional.lifecycle?.certification?.state ?? 'not_certified' }, modules, lessons, progress: progressSnap.docs.map((doc) => safeProgress(doc.data())) };
}

export async function completeLmsLesson(input: { actor: AuthorizedActor; moduleId: string; lessonId: string; idempotencyKey: string; db?: Firestore }) {
  const db = dbOr(input.db); await assertTrainingProfessional(db, input.actor.uid); const receiptRef = db.collection('lms_command_receipts').doc(`${input.actor.uid}_${input.idempotencyKey}`); const progressRef = db.collection('lms_progress').doc(input.actor.uid).collection('modules').doc(input.moduleId); const lessonRef = db.collection('lessons').doc(input.lessonId);
  await db.runTransaction(async (tx) => { const [receipt, lesson, progress] = await Promise.all([tx.get(receiptRef), tx.get(lessonRef), tx.get(progressRef)]); if (receipt.exists) return; if (!lesson.exists || lesson.data()?.status !== 'published' || lesson.data()?.moduleId !== input.moduleId) throw new HttpError(404, 'LMS_LESSON_NOT_FOUND', 'Published lesson was not found'); const completed = new Set(Array.isArray(progress.data()?.lessonsCompleted) ? progress.data()!.lessonsCompleted.map(String) : []); completed.add(input.lessonId); tx.set(progressRef, { schemaVersion: 1, professionalUid: input.actor.uid, moduleId: input.moduleId, lessonsCompleted: [...completed], updatedAt: now }, { merge: true }); tx.create(receiptRef, { schemaVersion: 1, actorUid: input.actor.uid, command: 'lesson.complete', result: { moduleId: input.moduleId, lessonId: input.lessonId }, createdAt: now }); audit(db, tx, input.actor.uid, 'lms.lesson.completed', `lms_progress/${input.actor.uid}/modules/${input.moduleId}`, { lessonId: input.lessonId }); });
  return { moduleId: input.moduleId, lessonId: input.lessonId, acknowledged: true };
}
function sanitizeAttempt(doc: FirebaseFirestore.DocumentSnapshot) { const data = doc.data()!; return { attemptId: doc.id, state: data.state, questions: (data.questionSnapshot ?? []).map(toClientQuestion), resumed: data.state === 'in_progress' }; }
async function createOrResumeAttempt(input: { actor: AuthorizedActor; scope: 'module' | 'final'; moduleId?: string; idempotencyKey: string; db?: Firestore }) {
  const db = dbOr(input.db); await assertTrainingProfessional(db, input.actor.uid); const receiptRef = db.collection('lms_command_receipts').doc(`${input.actor.uid}_${input.idempotencyKey}`); const attempts = db.collection(input.scope === 'final' ? 'lms_final_exam_attempts' : 'lms_module_attempts');
  const previousReceipt = await receiptRef.get();
  if (previousReceipt.exists) {
    const attemptId = String(previousReceipt.data()?.result?.attemptId ?? ''); const existing = attemptId ? await attempts.doc(attemptId).get() : null;
    if (existing?.exists) return sanitizeAttempt(existing);
    throw new HttpError(409, 'LMS_IDEMPOTENCY_RECONCILIATION_REQUIRED', 'Command receipt requires reconciliation');
  }
  const active = await attempts.where('professionalUid', '==', input.actor.uid).where('state', '==', 'in_progress').limit(1).get(); if (!active.empty) return sanitizeAttempt(active.docs[0]);
  let questions: FirebaseFirestore.DocumentData[] = [];
  if (input.scope === 'module') { const module = await db.collection('modules').doc(input.moduleId!).get(); if (!module.exists || module.data()?.status !== 'published') throw new HttpError(404, 'LMS_MODULE_NOT_FOUND', 'Published module was not found'); const progress = await db.collection('lms_progress').doc(input.actor.uid).collection('modules').doc(input.moduleId!).get(); const allLessons = await db.collection('lessons').where('moduleId', '==', input.moduleId).where('status', '==', 'published').get(); const completed = new Set(Array.isArray(progress.data()?.lessonsCompleted) ? progress.data()!.lessonsCompleted.map(String) : []); if (allLessons.docs.some((lesson) => !completed.has(lesson.id))) throw new HttpError(409, 'LMS_LESSONS_INCOMPLETE', 'All published lessons must be acknowledged first'); const evaluation = await db.collection('evaluations').doc(String(module.data()?.evaluationId ?? '')).get(); if (!evaluation.exists || evaluation.data()?.status !== 'published') throw new HttpError(409, 'LMS_EVALUATION_UNAVAILABLE', 'Published evaluation is unavailable'); questions = Array.isArray(evaluation.data()?.questions) ? evaluation.data()!.questions : []; }
  else { const [evaluations, finalQuestions] = await Promise.all([db.collection('evaluations').where('status', '==', 'published').get(), db.collection('final_exam_questions').where('status', '==', 'published').get()]); questions = evaluations.docs.flatMap((doc) => Array.isArray(doc.data().questions) ? doc.data().questions : []).concat(finalQuestions.docs.map((doc) => doc.data())); }
  if (!questions.length) throw new HttpError(409, 'LMS_CONTENT_UNAVAILABLE', 'Published assessment content is unavailable'); const ref = attempts.doc();
  const created = await db.runTransaction(async (tx) => { const receipt = await tx.get(receiptRef); if (receipt.exists) return false; tx.create(ref, { schemaVersion: 1, professionalUid: input.actor.uid, scope: input.scope, moduleId: input.moduleId ?? null, state: 'in_progress', questionSnapshot: questions, createdAt: now, updatedAt: now }); tx.create(receiptRef, { schemaVersion: 1, actorUid: input.actor.uid, command: `${input.scope}_assessment.start`, result: { attemptId: ref.id }, createdAt: now }); audit(db, tx, input.actor.uid, `lms.${input.scope}_assessment.started`, `${attempts.id}/${ref.id}`, { moduleId: input.moduleId ?? null }); return true; });
  if (!created) { const receipt = await receiptRef.get(); const attemptId = String(receipt.data()?.result?.attemptId ?? ''); const existing = attemptId ? await attempts.doc(attemptId).get() : null; if (existing?.exists) return sanitizeAttempt(existing); throw new HttpError(409, 'LMS_IDEMPOTENCY_RECONCILIATION_REQUIRED', 'Command receipt requires reconciliation'); }
  return { attemptId: ref.id, state: 'in_progress', questions: questions.map(toClientQuestion), resumed: false };
}
export async function startModuleEvaluation(input: { actor: AuthorizedActor; moduleId: string; idempotencyKey: string; db?: Firestore }) { return createOrResumeAttempt({ ...input, scope: 'module' }); }
export async function startFinalExam(input: { actor: AuthorizedActor; idempotencyKey: string; db?: Firestore }) { return createOrResumeAttempt({ ...input, scope: 'final' }); }
async function submitAttempt(input: { actor: AuthorizedActor; scope: 'module' | 'final'; attemptId: string; answers: LmsAnswer[]; idempotencyKey: string; db?: Firestore }) {
  const db = dbOr(input.db); await assertTrainingProfessional(db, input.actor.uid); const attempts = db.collection(input.scope === 'final' ? 'lms_final_exam_attempts' : 'lms_module_attempts'); const attemptRef = attempts.doc(input.attemptId); const receiptRef = db.collection('lms_command_receipts').doc(`${input.actor.uid}_${input.idempotencyKey}`); let result: { attemptId: string; state: 'submitted'; scorePercent: number; policyState: typeof POLICY_STATE } | undefined;
  await db.runTransaction(async (tx) => { const [receipt, attempt] = await Promise.all([tx.get(receiptRef), tx.get(attemptRef)]); if (receipt.exists) { result = receipt.data()?.result as typeof result; return; } if (!attempt.exists || attempt.data()?.professionalUid !== input.actor.uid) throw new HttpError(404, 'LMS_ATTEMPT_NOT_FOUND', 'Assessment attempt was not found'); const data = attempt.data()!; if (data.state === 'submitted') { result = { attemptId: attempt.id, state: 'submitted', scorePercent: Number(data.scorePercent ?? 0), policyState: POLICY_STATE }; tx.create(receiptRef, { schemaVersion: 1, actorUid: input.actor.uid, command: `${input.scope}_assessment.submit`, result, createdAt: now }); return; } const snapshot = Array.isArray(data.questionSnapshot) ? data.questionSnapshot : []; const allowedIds = new Set(snapshot.map((question: Record<string, unknown>) => String(question.id))); if (input.answers.some((answer) => !allowedIds.has(answer.questionId))) throw new HttpError(400, 'INVALID_PAYLOAD', 'Answer references an unknown question'); const graded = gradeServerQuestionSnapshot(snapshot, input.answers); result = { attemptId: attempt.id, state: 'submitted', scorePercent: graded.scorePercent, policyState: POLICY_STATE }; tx.update(attemptRef, { state: 'submitted', answers: graded.privateAnswers, scorePercent: graded.scorePercent, policyState: POLICY_STATE, submittedAt: now, updatedAt: now }); if (input.scope === 'module') tx.set(db.collection('lms_progress').doc(input.actor.uid).collection('modules').doc(String(data.moduleId)), { evaluation: { state: 'submitted', scorePercent: graded.scorePercent, policyState: POLICY_STATE, attemptId: attempt.id }, updatedAt: now }, { merge: true }); tx.create(receiptRef, { schemaVersion: 1, actorUid: input.actor.uid, command: `${input.scope}_assessment.submit`, result, createdAt: now }); audit(db, tx, input.actor.uid, `lms.${input.scope}_assessment.submitted`, `${attempts.id}/${attempt.id}`, { scorePercent: graded.scorePercent, policyState: POLICY_STATE }); }); return result!;
}
export async function submitModuleEvaluation(input: { actor: AuthorizedActor; attemptId: string; answers: LmsAnswer[]; idempotencyKey: string; db?: Firestore }) { return submitAttempt({ ...input, scope: 'module' }); }
export async function submitFinalExam(input: { actor: AuthorizedActor; attemptId: string; answers: LmsAnswer[]; idempotencyKey: string; db?: Firestore }) { return submitAttempt({ ...input, scope: 'final' }); }
export async function getLmsCertificate(input: { actor: AuthorizedActor; db?: Firestore }) { const db = dbOr(input.db); const professional = await assertTrainingProfessional(db, input.actor.uid); if (professional.lifecycle?.certification?.state !== 'certified') return null; const certificates = await db.collection('certifications').where('professionalUid', '==', input.actor.uid).where('valid', '==', true).limit(1).get(); if (certificates.empty) return null; const data = certificates.docs[0].data(); return { employeeName: String(data.employeeName ?? ''), code: certificates.docs[0].id, level: String(data.level ?? 'Formação Método Pame'), issuedAt: data.issuedAt ?? null, score: typeof data.finalExamScorePercent === 'number' ? data.finalExamScorePercent : null, disclaimer: 'A certificação reconhece formação; não informa ativação operacional nem autorização de trabalho.' }; }
export async function verifyLmsCertificate(input: { certificateCode: string; db?: Firestore }) { const snap = await dbOr(input.db).collection('certifications').doc(input.certificateCode).get(); if (!snap.exists || snap.data()?.valid !== true) return { valid: false }; const data = snap.data()!; return { valid: true, employeeName: String(data.employeeName ?? ''), level: String(data.level ?? 'Formação Método Pame'), issuedAt: data.issuedAt ?? null, disclaimer: 'Este resultado verifica somente o certificado de formação. Não confirma ativação operacional ou autorização de trabalho.' }; }
