import { useEffect, useState } from 'react';
import type { Employee } from '../types';
import type { LmsClientQuestion } from '../../shared/lms-domain';
import { lmsApi, lmsCommandKey } from '../lib/lms-api';

interface LMSEvaluationProps { employee: Employee; moduleSlug?: string; onNavigate: (view: 'overview' | 'module' | 'lesson' | 'evaluation' | 'certificate', param?: string, lessonNumber?: number) => void; isAdminView?: boolean; }
type Start = { attemptId: string; state: string; questions: LmsClientQuestion[]; resumed: boolean };
type Catalog = { modules: Array<{ id: string; slug: string }> };

export default function LMSEvaluation({ moduleSlug, onNavigate, isAdminView = false }: LMSEvaluationProps) {
  const final = !moduleSlug; const [attempt, setAttempt] = useState<Start | null>(null); const [answers, setAnswers] = useState<Record<string, string>>({}); const [error, setError] = useState(''); const [submitting, setSubmitting] = useState(false); const [result, setResult] = useState<{ scorePercent: number } | null>(null);
  useEffect(() => { if (isAdminView) return; (async () => { try { let moduleId: string | undefined; if (!final) { const catalog = await lmsApi<Catalog>('catalog'); moduleId = catalog.modules.find((item) => item.slug === moduleSlug)?.id; if (!moduleId) throw new Error('Módulo não encontrado.'); } const started = await lmsApi<Start>(final ? 'final.start' : 'module.start', { method: 'POST', body: final ? { idempotencyKey: lmsCommandKey('final-start') } : { moduleId, idempotencyKey: lmsCommandKey('module-start') } }); setAttempt(started); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Não foi possível iniciar a avaliação.'); } })(); }, [final, isAdminView, moduleSlug]);
  const submit = async () => { if (!attempt) return; setSubmitting(true); setError(''); try { const response = await lmsApi<{ scorePercent: number }>(final ? 'final.submit' : 'module.submit', { method: 'POST', body: { attemptId: attempt.attemptId, answers: attempt.questions.map((question) => ({ questionId: question.id, answer: answers[question.id] ?? '' })), idempotencyKey: lmsCommandKey(final ? 'final-submit' : 'module-submit') } }); setResult(response); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Não foi possível enviar a avaliação.'); } finally { setSubmitting(false); } };
  if (isAdminView) return <div className="py-16 text-center text-sm text-[#80737f]">Avaliações são privadas; o modo de monitoramento mostra apenas o progresso agregado.</div>;
  if (!attempt && !error) return <div className="py-20 text-center">Preparando avaliação...</div>; if (error) return <div className="py-20 text-center text-[#ba1a1a]">{error}<button className="block mx-auto mt-5 text-[#561668]" onClick={() => onNavigate('overview')}>Voltar</button></div>;
  if (result) return <div className="max-w-xl mx-auto px-4 py-16 text-center"><h1 className="text-3xl font-display italic text-[#561668]">Avaliação enviada</h1><p className="mt-4 text-[#80737f]">Nota registrada: {result.scorePercent}%.</p><p className="mt-2 text-xs text-[#80737f]">O critério de aprovação e qualquer decisão de conclusão permanecem sob política humana. Esta nota não certifica nem ativa operações.</p><button className="mt-8 bg-[#561668] text-white px-5 py-3 rounded-xl text-xs" onClick={() => onNavigate('overview')}>Voltar ao portal</button></div>;
  return <div className="max-w-3xl mx-auto px-4 py-8"><button className="text-xs text-[#561668] mb-6" onClick={() => onNavigate('overview')}>← Voltar</button><h1 className="text-3xl font-display italic text-[#561668]">{final ? 'Exame final' : 'Avaliação do módulo'}</h1><p className="text-xs text-[#80737f] mt-2">As respostas e critérios de correção ficam no servidor.</p><div className="mt-8 grid gap-6">{attempt!.questions.map((question, index) => <section key={question.id} className="bg-white border border-[#efe5ee] p-5 rounded-2xl"><p className="font-bold text-[#1e1a20]">{index + 1}. {question.question}</p>{question.type === 'multiple_choice' ? <div className="mt-4 grid gap-2">{question.options?.map((option, optionIndex) => <label key={optionIndex} className="text-sm"><input className="mr-2" type="radio" name={question.id} checked={answers[question.id] === String(optionIndex)} onChange={() => setAnswers({ ...answers, [question.id]: String(optionIndex) })} />{option}</label>)}</div> : <textarea className="w-full mt-4 min-h-28 border border-[#efe5ee] rounded-xl p-3 text-sm" value={answers[question.id] ?? ''} onChange={(event) => setAnswers({ ...answers, [question.id]: event.target.value })} />}</section>)}</div><button disabled={submitting} className="mt-8 bg-[#561668] disabled:bg-[#80737f] text-white px-5 py-3 rounded-xl text-xs font-bold" onClick={submit}>{submitting ? 'Enviando...' : 'Enviar avaliação'}</button></div>;
}
