import { useEffect, useState } from 'react';
import type { Employee, LMSLesson, LMSModule } from '../types';
import { lmsApi, lmsCommandKey } from '../lib/lms-api';

interface LMSLessonProps { employee: Employee; moduleSlug: string; lessonNumber: number; onNavigate: (view: 'overview' | 'module', param?: string) => void; isAdminView?: boolean; adminTargetEmployeeId?: string; }
type Catalog = { modules: LMSModule[]; lessons: LMSLesson[] };

export default function LMSLesson({ moduleSlug, lessonNumber, onNavigate, isAdminView = false, adminTargetEmployeeId }: LMSLessonProps) {
  const [catalog, setCatalog] = useState<Catalog | null>(null); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const [done, setDone] = useState(false);
  useEffect(() => { lmsApi<Catalog>('catalog', { query: isAdminView && adminTargetEmployeeId ? { professionalUid: adminTargetEmployeeId } : {} }).then(setCatalog).catch((reason) => setError(reason.message)); }, [isAdminView, adminTargetEmployeeId]);
  if (!catalog && !error) return <div className="py-20 text-center">Carregando lição...</div>; if (error) return <div className="py-20 text-center text-[#ba1a1a]">{error}</div>;
  const module = catalog!.modules.find((item) => item.slug === moduleSlug); const lesson = catalog!.lessons.find((item) => item.moduleId === module?.id && item.number === lessonNumber); if (!module || !lesson) return <div className="py-20 text-center">Lição não encontrada.</div>;
  const acknowledge = async () => { if (isAdminView) return; setSaving(true); setError(''); try { await lmsApi('lesson.complete', { method: 'POST', body: { moduleId: module.id, lessonId: lesson.id, idempotencyKey: lmsCommandKey('lesson') } }); setDone(true); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Não foi possível registrar a lição.'); } finally { setSaving(false); } };
  return <div className="max-w-3xl mx-auto px-4 py-8"><button className="text-xs text-[#561668] mb-6" onClick={() => onNavigate('module', module.slug)}>← Voltar ao módulo</button><p className="text-xs text-[#C9A84C] uppercase tracking-widest">Módulo {module.number} · Lição {lesson.number}</p><h1 className="text-3xl font-display italic text-[#561668] mt-2">{lesson.title}</h1>{lesson.videoUrl && <video className="w-full rounded-2xl mt-6" controls src={lesson.videoUrl} />}{lesson.content && <article className="mt-6 prose max-w-none whitespace-pre-wrap text-[#403840]">{lesson.content}</article>}<p className="mt-8 text-xs text-[#80737f]">Ao confirmar, você registra apenas a conclusão declarada desta lição. Não altera certificação nem ativação operacional.</p>{!isAdminView && <button disabled={saving || done} onClick={acknowledge} className="mt-3 bg-[#561668] disabled:bg-[#80737f] text-white px-5 py-3 rounded-xl text-xs font-bold">{done ? 'Conclusão registrada' : saving ? 'Registrando...' : lesson.completionCriteria?.buttonLabel ?? 'Marcar como concluída'}</button>}{error && <p className="mt-3 text-xs text-[#ba1a1a]">{error}</p>}</div>;
}
