import React, { useEffect, useState } from 'react';

interface VerifyCertificateProps { certificateCode?: string; onBackToApp?: () => void; }
type VerifiedCertificate = { valid: boolean; employeeName?: string; level?: string; issuedAt?: { seconds?: number }; disclaimer?: string };

export default function VerifyCertificate({ certificateCode: propCode, onBackToApp }: VerifyCertificateProps) {
  const [code, setCode] = useState(propCode ?? ''); const [result, setResult] = useState<VerifiedCertificate | null>(null); const [loading, setLoading] = useState(false);
  const verify = async (value: string) => { const trimmed = value.trim(); if (!trimmed) return; setLoading(true); setResult(null); try { const response = await fetch(`/api/lms?action=verify-certificate&code=${encodeURIComponent(trimmed)}`, { cache: 'no-store' }); setResult(await response.json()); } catch { setResult({ valid: false }); } finally { setLoading(false); } };
  useEffect(() => { if (propCode) void verify(propCode); }, [propCode]);
  return <div className="min-h-screen bg-[#fff7fd] flex items-center justify-center px-4"><main className="w-full max-w-md bg-white border border-[#efe5ee] rounded-3xl p-8"><div className="flex justify-between gap-4"><div><p className="text-xs uppercase tracking-widest text-[#C9A84C]">Método Pame</p><h1 className="text-2xl font-bold text-[#561668] mt-2">Verificar certificado</h1></div>{onBackToApp && <button onClick={onBackToApp} className="text-xs text-[#561668]">Voltar</button>}</div><p className="text-xs text-[#80737f] mt-3">A verificação confirma somente a autenticidade do certificado de formação.</p><form className="flex gap-2 mt-6" onSubmit={(event) => { event.preventDefault(); void verify(code); }}><input className="min-w-0 flex-1 border border-[#efe5ee] rounded-xl px-3 text-xs" value={code} onChange={(event) => setCode(event.target.value)} placeholder="Código do certificado" required /><button className="bg-[#561668] text-white px-4 py-3 rounded-xl text-xs" disabled={loading}>{loading ? '...' : 'Verificar'}</button></form>{result && <section className={`mt-6 rounded-2xl p-5 text-sm ${result.valid ? 'bg-[#fffdf9] border border-[#C9A84C]/40' : 'bg-[#fff7fd] border border-[#ba1a1a]/20'}`}><b className={result.valid ? 'text-[#561668]' : 'text-[#ba1a1a]'}>{result.valid ? 'CERTIFICADO VÁLIDO' : 'Registro não encontrado ou inválido'}</b>{result.valid && <><p className="mt-3">{result.employeeName}</p><p className="text-xs text-[#80737f] mt-1">{result.level}</p><p className="text-xs text-[#80737f] mt-4">{result.disclaimer}</p></>}</section>}</main></div>;
}
